name: release

on:
  workflow_dispatch:
  push:
    branches:
      - release

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-tauri:
    name: Build desktop bundles
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            args: "--target aarch64-apple-darwin"
          - platform: macos-latest
            args: "--target x86_64-apple-darwin"
          - platform: ubuntu-22.04
            args: ""
          - platform: windows-latest
            args: ""
    permissions:
      contents: write
    outputs:
      release_id: ${{ steps.publish.outputs.releaseId }}
      release_upload_url: ${{ steps.publish.outputs.releaseUploadUrl }}
      app_version: ${{ steps.publish.outputs.appVersion }}
    steps:
      - uses: actions/checkout@v4

      - name: Install system deps (Ubuntu)
        if: contains(matrix.platform, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Setup Rust (macOS targets)
        if: matrix.platform == 'macos-latest'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Setup Rust (other platforms)
        if: matrix.platform != 'macos-latest'
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            ./src-tauri -> target

      - name: Install frontend dependencies
        run: npm ci

      - name: Build with tauri-action
        id: publish
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          TAURI_SIGNING_PRIVATE_KEY: "${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}"
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: "${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}"
          TAURI_UPDATER_PUBKEY: "${{ secrets.TAURI_UPDATER_PUBKEY }}"
          TAURI_UPDATER_ENDPOINT: "${{ secrets.TAURI_UPDATER_ENDPOINT }}"
        with:
          tagName: app-v__VERSION__
          releaseName: 明日方舟剧情阅读器 v__VERSION__
          releaseBody: |
            自动构建版本。请在附件中获取对应平台的安装包。
          releaseDraft: true
          args: ${{ matrix.args }}

  android:
    name: Build signed Android APK
    needs: publish-tauri
    if: ${{ needs.publish-tauri.result == 'success' && secrets.ANDROID_KEYSTORE_B64 != '' }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            tools
            platform-tools
            platforms;android-36
            build-tools;36.0.0
            ndk;26.1.10909125

      - name: Setup Rust (Android target)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            ./src-tauri -> target

      - name: Install frontend dependencies
        run: npm ci

      - name: Restore Android keystore
        env:
          ANDROID_KEYSTORE_B64: "${{ secrets.ANDROID_KEYSTORE_B64 }}"
          ANDROID_KEYSTORE_PASSWORD: "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}"
          ANDROID_KEY_ALIAS: "${{ secrets.ANDROID_KEY_ALIAS }}"
          ANDROID_KEY_PASSWORD: "${{ secrets.ANDROID_KEY_PASSWORD }}"
          WORKSPACE_PATH: "${{ github.workspace }}"
        run: |
          mkdir -p src-tauri/gen/android
          echo "$ANDROID_KEYSTORE_B64" | base64 --decode > src-tauri/gen/android/upload-keystore.jks

          KEY_PASSWORD="${ANDROID_KEY_PASSWORD:-$ANDROID_KEYSTORE_PASSWORD}"
          {
            echo "storePassword=${ANDROID_KEYSTORE_PASSWORD}"
            echo "keyPassword=${KEY_PASSWORD}"
            echo "keyAlias=${ANDROID_KEY_ALIAS}"
            echo "storeFile=${WORKSPACE_PATH}/src-tauri/gen/android/upload-keystore.jks"
          } > src-tauri/gen/android/keystore.properties

      - name: Build signed Android APK
        env:
          ANDROID_KEYSTORE_PATH: "${{ github.workspace }}/src-tauri/gen/android/upload-keystore.jks"
          ANDROID_KEY_ALIAS: "${{ secrets.ANDROID_KEY_ALIAS }}"
          ANDROID_KEYSTORE_PASSWORD: "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}"
          ANDROID_KEY_PASSWORD: "${{ secrets.ANDROID_KEY_PASSWORD }}"
        run: bash scripts/build-apk.sh

      - name: Upload APK to release
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          APP_VERSION: "${{ needs.publish-tauri.outputs.app_version }}"
        run: |
          APK_PATH="src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-signed.apk"
          if [ ! -f "$APK_PATH" ]; then
            echo "Signed APK not found at $APK_PATH" >&2
            exit 1
          fi
          TAG="app-v$APP_VERSION"
          RELEASE_NAME="arknights-story-reader-android-$APP_VERSION.apk"
          gh release upload "$TAG" "$APK_PATH#$RELEASE_NAME" --clobber

      - name: Publish Android update manifest
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          REPO: "${{ github.repository }}"
          APP_VERSION: "${{ needs.publish-tauri.outputs.app_version }}"
        run: |
          TAG="app-v$APP_VERSION"
          APK_NAME="arknights-story-reader-android-$APP_VERSION.apk"
          JSON_PATH="android-latest.json"
          printf '{
            "version": "%s",
            "notes": "",
            "url": "https://github.com/%s/releases/download/%s/%s",
            "fileName": "%s"
          }' "$APP_VERSION" "$REPO" "$TAG" "$APK_NAME" "$APK_NAME" > "$JSON_PATH"
          gh release upload "$TAG" "$JSON_PATH#$JSON_PATH" --clobber

      - name: Cleanup keystore
        if: always()
        run: rm -f src-tauri/gen/android/upload-keystore.jks src-tauri/gen/android/keystore.properties
